[manifest]
version = "0.1"
dump_lua = false
priority = 0

# Замена шрифта (для редактирования - измените параметры в строке "payload"), TEXT_HEIGHT_SCALE - межстрочный интервал, self.TILESIZE - размер UI кнопок с текстом, 
# TEXT_OFFSET - смещение текста, FONTSCALE - размер шрифта, DESCSCALE - размер описаний карт
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = '''{file = "resources/fonts/NotoSans-Bold.ttf", render_scale = self.TILESIZE*7, TEXT_HEIGHT_SCALE = 0.65, TEXT_OFFSET = {x=0,y=-40}, FONTSCALE = 0.12, squish = 1, DESCSCALE = 1},'''
position = "at"
payload = '''{file = "resources/fonts/NotoSans-Bold.ttf", render_scale = self.TILESIZE*10, TEXT_HEIGHT_SCALE = 0.65, TEXT_OFFSET = {x=0,y=-40}, FONTSCALE = 0.13, squish = 1, DESCSCALE = 1},'''
overwrite = true
match_indent = true

# Локализация для строки "Not Allowed!"
[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '''play_area_status_text("Not Allowed!")--localize('k_not_allowed_ex'), true)'''
position = "at"
payload = '''play_area_status_text(localize('k_not_allowed_ex'))'''
overwrite = true
match_indent = true

# Исправление центрирования кнопки "Сыграть руку"
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''local play_button = {n=G.UIT.C, config={id = 'play_button', align = "tm", minw = 2.5, padding = 0.3, r = 0.1, hover = true, colour = G.C.BLUE, button = "play_cards_from_highlighted", one_press = true, shadow = true, func = 'can_play'}, nodes={'''
position = "at"
payload = '''local play_button = {n=G.UIT.C, config={id = 'play_button', align = "cm", minw = 2.5, padding = 0.3, r = 0.1, hover = true, colour = G.C.BLUE, button = "play_cards_from_highlighted", one_press = true, shadow = true, func = 'can_play'}, nodes={'''
overwrite = true
match_indent = true

# Исправление центрирования кнопки "Сбросить"
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''local discard_button = {n=G.UIT.C, config={id = 'discard_button',align = "tm", padding = 0.3, r = 0.1, minw = 2.5, minh = button_height, hover = true, colour = G.C.RED, button = "discard_cards_from_highlighted", one_press = true, shadow = true, func = 'can_discard'}, nodes={'''
position = "at"
payload = '''local discard_button = {n=G.UIT.C, config={id = 'discard_button',align = "cm", padding = 0.3, r = 0.1, minw = 2.5, minh = button_height, hover = true, colour = G.C.RED, button = "discard_cards_from_highlighted", one_press = true, shadow = true, func = 'can_discard'}, nodes={'''
overwrite = true
match_indent = true

# Исправление центрирования кнопки "Пропустить"
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.R,config={align = "tm",padding = 0.2, minh = 1.2, minw = 1.8, r=0.15,colour = G.C.GREY, one_press = true, button = 'skip_booster', hover = true,shadow = true, func = 'can_skip_booster'}, nodes = {'''
position = "at"
payload = '''{n=G.UIT.R,config={align = "cm",padding = 0.2, minh = 1.2, minw = 1.8, r=0.15,colour = G.C.GREY, one_press = true, button = 'skip_booster', hover = true,shadow = true, func = 'can_skip_booster'}, nodes = {'''
overwrite = true
match_indent = true

# Локализация для строки "Round score"
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.T, config={text = localize('k_round'), scale = 0.42, colour = G.C.UI.TEXT_LIGHT, shadow = true}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = "Текущий", scale = 0.42, colour = G.C.UI.TEXT_LIGHT, shadow = true}}'''
overwrite = true
match_indent = true
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.T, config={text =localize('k_lower_score'), scale = 0.42, colour = G.C.UI.TEXT_LIGHT, shadow = true}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = "счёт", scale = 0.42, colour = G.C.UI.TEXT_LIGHT, shadow = true}}'''
overwrite = true
match_indent = true

# Исправление размера текста на кнопке "Next round"
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.R, config={align = "cm", maxw = 1.3}, nodes={'''
position = "at"
payload = '''{n=G.UIT.R, config={align = "cm", maxw = 2}, nodes={'''
overwrite = true
match_indent = true

# Локализация для строки "View deck"
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''{n=G.UIT.T, config={text = localize('k_deck'), scale = 0.38, colour = G.C.WHITE, shadow = true}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = "колоду", scale = 0.38, colour = G.C.WHITE, shadow = true}}'''
overwrite = true
match_indent = true

# Локализация и местоположение строки "PEEK DECK" при игре с геймпадом
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''{n=G.UIT.T, config={text = 'PEEK', scale = 0.48, colour = G.C.WHITE, shadow = true}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = "Оставшиеся", scale = 0.35, colour = G.C.WHITE, shadow = true}}'''
overwrite = true
match_indent = true
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''{n=G.UIT.T, config={text = 'DECK', scale = 0.38, colour = G.C.WHITE, shadow = true}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = "карты", scale = 0.4, colour = G.C.WHITE, shadow = true}}'''
overwrite = true
match_indent = true
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''config = { align = 'cl', offset = {x=-0.5,y=0.1}, major = self, parent = self}'''
position = "at"
payload = '''config = { align = 'bl', offset = {x=-10.78,y=-1.45}, major = self, parent = self}'''
overwrite = true
match_indent = true

# Локализация для отсутствующей строки "DEFEAT BOSS-BLIND TO RESTOCK"
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''elseif G.SETTINGS.language ~= 'en-us' then'''
position = "at"
payload = '''elseif G.SETTINGS.language == 'zh_TW' then'''
overwrite = true
match_indent = true
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''{n=G.UIT.T, config={text = 'DEFEAT', scale = 0.6, colour = G.C.WHITE}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = 'ПОБЕДИТЕ', scale = 0.4, colour = G.C.WHITE}}'''
overwrite = true
match_indent = true
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''{n=G.UIT.T, config={text = 'BOSS BLIND', scale = 0.4, colour = G.C.WHITE}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = 'БОСС-БЛАЙНД', scale = 0.4, colour = G.C.WHITE}}'''
overwrite = true
match_indent = true
[[patches]]
[patches.pattern]
target = "cardarea.lua"
pattern = '''{n=G.UIT.T, config={text = 'TO RESTOCK', scale = 0.4, colour = G.C.WHITE}}'''
position = "at"
payload = '''{n=G.UIT.T, config={text = 'ДЛЯ ПОПОЛНЕНИЯ', scale = 0.4, colour = G.C.WHITE}}'''
overwrite = true
match_indent = true

# Использование корректного шрифта для кол-ва рук/сбросов/денег/анте в интерфейсе
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME.current_round, ref_value = 'hands_left'}}, font = G.LANGUAGES['en-us'].font, colours = {G.C.BLUE},shadow = true, rotate = true, scale = 2*scale}),id = 'hand_UI_count'}},'''
position = "at"
payload = '''{n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME.current_round, ref_value = 'hands_left'}}, font = G.LANGUAGES['ru'].font, colours = {G.C.BLUE},shadow = true, rotate = true, scale = 2*scale}),id = 'hand_UI_count'}},'''
overwrite = true
match_indent = true
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME.current_round, ref_value = 'discards_left'}}, font = G.LANGUAGES['en-us'].font, colours = {G.C.RED},shadow = true, rotate = true, scale = 2*scale}),id = 'discard_UI_count'}},'''
position = "at"
payload = '''{n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME.current_round, ref_value = 'discards_left'}}, font = G.LANGUAGES['ru'].font, colours = {G.C.RED},shadow = true, rotate = true, scale = 2*scale}),id = 'discard_UI_count'}},'''
overwrite = true
match_indent = true
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME, ref_value = 'dollars', prefix = localize('$')}}, maxw = 1.35, colours = {G.C.MONEY}, font = G.LANGUAGES['en-us'].font, shadow = true,spacing = 2, bump = true, scale = 2.2*scale}), id = 'dollar_text_UI'}}'''
position = "at"
payload = '''{n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME, ref_value = 'dollars', prefix = localize('$')}}, maxw = 1.8, colours = {G.C.MONEY}, font = G.LANGUAGES['ru'].font, shadow = true,spacing = 2, bump = true, scale = 2.2*scale}), id = 'dollar_text_UI'}}'''
overwrite = true
match_indent = true
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME.round_resets, ref_value = 'ante'}}, colours = {G.C.IMPORTANT},shadow = true, font = G.LANGUAGES['en-us'].font, scale = 2*scale}),id = 'ante_UI_count'}},'''
position = "at"
payload = '''{n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME.round_resets, ref_value = 'ante'}}, colours = {G.C.IMPORTANT},shadow = true, font = G.LANGUAGES['ru'].font, scale = 2*scale}),id = 'ante_UI_count'}},'''
overwrite = true
match_indent = true

# Локализация для названий комбинаций при использовании Орбитального жетона
[[patches]]
[patches.pattern]
target = "tag.lua"
pattern = '''handname= self.ability.orbital_hand,'''
position = "at"
payload = '''handname = localize(self.ability.orbital_hand, "poker_hands"),'''
overwrite = true
match_indent = true

# Исправление текста в названиях мастей в меню Особых рубашек для карт
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''label = localize('Spades', 'suits_plural'),'''
position = "at"
payload = '''label = localize('Spades', 'suits_singular'),'''
overwrite = true
match_indent = true
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''label = localize('Hearts', 'suits_plural'),'''
position = "at"
payload = '''label = localize('Hearts', 'suits_singular'),'''
overwrite = true
match_indent = true
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''label = localize('Clubs', 'suits_plural'),'''
position = "at"
payload = '''label = localize('Clubs', 'suits_singular'),'''
overwrite = true
match_indent = true
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''label = localize('Diamonds', 'suits_plural'),'''
position = "at"
payload = '''label = localize('Diamonds', 'suits_singular'),'''
overwrite = true
match_indent = true

# Замена форматирования разрядов чисел с запятых на пробелы (1,000 => 1 000)
[[patches]]
[patches.regex]
target = "functions/misc_functions.lua"
pattern = 'gsub\("\(%d%d%d\)"\, "%1,"\):gsub\("\,\$"\, ""\)'
position = "at"
payload = 'gsub("(%d%d%d)", "%1 "):gsub(" $", "")'

# Добавление ссылки на локализацию в меню Авторы
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = '''love.system.openURL( "https://www.instagram.com/louisfsoundtracks/" )'''
position = "after"
payload = '''
			end
			
			G.FUNCS.nitablade_github = function(e)
			love.system.openURL( "https://github.com/Nitablade/Balatro_ProperRussian/releases/" )
			end
			
			G.FUNCS.nitablade_twitch = function(e)
			love.system.openURL( "https://www.twitch.tv/Nitablade" )
		  '''
overwrite = false
match_indent = true
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = '''{n=G.UIT.T, config={text = "Modified with their permission", scale = text_scale*0.5, colour = G.C.UI.TEXT_LIGHT, shadow = true}},'''
position = "after"
payload = '''
			}},
			{n=G.UIT.R, config={align = "cm", padding = 0.32}, nodes={
			  {n=G.UIT.T, config={text = "Локализация от", scale = text_scale*0.8, colour = G.C.UI.TEXT_LIGHT, shadow = true}},
			  {n=G.UIT.T, config={text = "Nitablade", scale = text_scale*0.8, colour = HEX("ff004e"), shadow = true}}
			}},
			G.F_EXTERNAL_LINKS and {n=G.UIT.R, config={align = "cm", padding = 0.1}, nodes={
               UIBox_button({label = {'Github'}, button = 'nitablade_github'}),
               UIBox_button({label = {'Twitch'}, button = 'nitablade_twitch'})
			}} or nil,
			{n=G.UIT.R, config={align = "cm", padding = 0.2}, nodes={
              {n=G.UIT.T, config={text = "Текущая версия локализации: 1.1.8", scale = text_scale*0.5, colour = G.C.UI.TEXT_LIGHT, shadow = true}},
		  '''
overwrite = false
match_indent = true

# Текущая версия локализации
[[patches]]
[patches.pattern]
target = "globals.lua"
pattern = "VERSION = VERSION..'-FULL'"
position = "after"
payload = "VERSION = VERSION..' (Локализация от Nitablade, v.1.1.8)'"
overwrite = false
match_indent = true